version: "3.8"
networks:
  backend:
    driver: bridge
services:
  db:
    image: postgres:16.1-alpine3.19
    networks:
      - backend
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data        
volumes:
  postgres-data:
